import React from "react";
import type { NextPage } from "next";
import Head from "next/head";

import Header from "../layouts/Header";
import Services from "../components/Services";
import Projects from "../components/Projects";
import Contact from "../components/Contact";

const Home: NextPage = () => {
  return (
    <div data-scroll-container>
      <Head>
        <title>Blyncnov | Frontend Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fav.ico" />
      </Head>
      <div>
        <Header />
        <div className="Index__Layout">
          <Services />
          <Projects />
        </div>
        <Contact />
      </div>
    </div>
  );
};

export default Home;
